"""Generates the ATT&CK coverage picture from detections/ + journal/:
an ATT&CK Navigator layer JSON, and a self-contained HTML report.
"""

from __future__ import annotations

import html
import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

from . import atomics, journal, sigma_pipeline

NAVIGATOR_COLOR_DETECTED = "#4caf50"
NAVIGATOR_COLOR_EXERCISED = "#ff9800"

LAYER_FILENAME = "navigator-layer.json"
REPORT_FILENAME = "report.html"


def detected_technique_ids(repo_root: Path) -> set[str]:
    """Techniques with a Sigma rule under detections/."""
    return {sigma_pipeline.technique_id_for(p) for p in sigma_pipeline.find_rules(repo_root / "detections")}


def build_navigator_layer(repo_root: Path) -> dict:
    detected = detected_technique_ids(repo_root)
    exercised = journal.covered_technique_ids(repo_root)

    techniques = []
    for t in atomics.load_techniques():
        if t.id in detected:
            techniques.append(
                {
                    "techniqueID": t.id,
                    "score": 100,
                    "color": NAVIGATOR_COLOR_DETECTED,
                    "comment": f"Sigma rule in detections/{t.tactic}/{t.id}.yml",
                    "enabled": True,
                }
            )
        elif t.id in exercised:
            techniques.append(
                {
                    "techniqueID": t.id,
                    "score": 40,
                    "color": NAVIGATOR_COLOR_EXERCISED,
                    "comment": "Exercised in the journal but no Sigma rule yet",
                    "enabled": True,
                }
            )

    return {
        "name": "Vanta Coverage",
        "versions": {"attack": "15", "navigator": "4.9.1", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": "Generated by `purplelab coverage` from detections/ and journal/.",
        "sorting": 0,
        "techniques": techniques,
        "gradient": {"colors": ["#ffffff", NAVIGATOR_COLOR_DETECTED], "minValue": 0, "maxValue": 100},
        "legendItems": [
            {"label": "Detected (Sigma rule deployed)", "color": NAVIGATOR_COLOR_DETECTED},
            {"label": "Exercised, no detection yet", "color": NAVIGATOR_COLOR_EXERCISED},
        ],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd",
    }


def tactic_breakdown(repo_root: Path) -> list[dict]:
    detected = detected_technique_ids(repo_root)
    by_tactic: dict[str, list] = defaultdict(list)
    for t in atomics.load_techniques():
        by_tactic[t.tactic].append(t)

    rows = []
    for tactic in sorted(by_tactic):
        techniques = by_tactic[tactic]
        covered = sum(1 for t in techniques if t.id in detected)
        rows.append(
            {
                "tactic": tactic,
                "covered": covered,
                "total": len(techniques),
                "pct": round(100 * covered / len(techniques)) if techniques else 0,
            }
        )
    return rows


def time_to_detect_series(repo_root: Path) -> list[dict]:
    entries = [e for e in journal.read_entries(repo_root) if e.time_to_detect_seconds is not None]
    entries.sort(key=lambda e: e.date)
    return [{"date": e.date, "technique_id": e.technique_id, "seconds": e.time_to_detect_seconds} for e in entries]


def build_html_report(repo_root: Path) -> str:
    detected = detected_technique_ids(repo_root)
    catalog = atomics.load_techniques()
    total = len(catalog)
    covered = len(detected)
    overall_pct = round(100 * covered / total) if total else 0

    tactics = tactic_breakdown(repo_root)
    streak = journal.current_streak_days(repo_root)
    ttd_series = time_to_detect_series(repo_root)
    gaps = [t for t in catalog if t.id not in detected]

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    tactic_rows = "\n".join(
        f'<tr><td>{html.escape(row["tactic"])}</td><td>{row["covered"]}/{row["total"]}</td>'
        f'<td><div class="bar"><div class="bar-fill" style="width:{row["pct"]}%"></div></div> {row["pct"]}%</td></tr>'
        for row in tactics
    )

    if ttd_series:
        max_s = max(p["seconds"] for p in ttd_series) or 1
        points = " ".join(
            f"{round(100 * i / max(len(ttd_series) - 1, 1))},{round(100 - 100 * p['seconds'] / max_s)}"
            for i, p in enumerate(ttd_series)
        )
        ttd_rows = "\n".join(
            f'<tr><td>{html.escape(p["date"])}</td><td>{html.escape(p["technique_id"])}</td>'
            f'<td>{p["seconds"]:.1f}s</td></tr>'
            for p in ttd_series
        )
        ttd_section = f"""
        <svg viewBox="0 0 100 100" preserveAspectRatio="none" class="sparkline">
          <polyline points="{points}" fill="none" stroke="currentColor" stroke-width="2" vector-effect="non-scaling-stroke"/>
        </svg>
        <table>
          <thead><tr><th>Date</th><th>Technique</th><th>Time to detect</th></tr></thead>
          <tbody>{ttd_rows}</tbody>
        </table>
        """
    else:
        ttd_section = "<p class=\"muted\">No time-to-detect data logged yet.</p>"

    gaps_rows = "\n".join(
        f'<li><code>{html.escape(t.id)}</code> — {html.escape(t.name)} '
        f'<span class="muted">[{html.escape(t.tactic)}]</span></li>'
        for t in gaps
    )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Vanta Coverage</title>
<style>
  :root {{
    --bg: #f7f7f8; --fg: #1a1a1a; --card: #ffffff; --border: #e0e0e0;
    --accent: #4caf50; --muted: #666666;
  }}
  @media (prefers-color-scheme: dark) {{
    :root {{ --bg: #17181a; --fg: #e8e8e8; --card: #1f2023; --border: #333333; --muted: #999999; }}
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0; padding: 24px 16px; background: var(--bg); color: var(--fg);
    font-family: -apple-system, Segoe UI, Roboto, sans-serif; line-height: 1.5;
  }}
  .wrap {{ max-width: 900px; margin: 0 auto; }}
  h1 {{ margin-bottom: 4px; }}
  .muted {{ color: var(--muted); font-size: 0.9em; }}
  .cards {{ display: flex; gap: 12px; flex-wrap: wrap; margin: 20px 0; }}
  .card {{
    background: var(--card); border: 1px solid var(--border); border-radius: 8px;
    padding: 16px 20px; min-width: 140px; flex: 1;
  }}
  .card .value {{ font-size: 2em; font-weight: 700; }}
  .card .label {{ color: var(--muted); font-size: 0.85em; }}
  table {{ width: 100%; border-collapse: collapse; margin: 12px 0; }}
  th, td {{ text-align: left; padding: 6px 8px; border-bottom: 1px solid var(--border); }}
  .bar {{ display: inline-block; width: 100px; height: 8px; background: var(--border); border-radius: 4px; overflow: hidden; vertical-align: middle; }}
  .bar-fill {{ height: 100%; background: var(--accent); }}
  .sparkline {{ width: 100%; height: 80px; color: var(--accent); }}
  ul {{ padding-left: 20px; }}
  code {{ background: var(--border); padding: 1px 5px; border-radius: 3px; }}
  section {{ margin: 28px 0; }}
</style>
</head>
<body>
<div class="wrap">
  <h1>Vanta Coverage</h1>
  <p class="muted">Generated {html.escape(generated_at)} by <code>purplelab coverage</code></p>

  <div class="cards">
    <div class="card"><div class="value">{overall_pct}%</div><div class="label">Overall coverage ({covered}/{total})</div></div>
    <div class="card"><div class="value">{streak}</div><div class="label">Day streak</div></div>
    <div class="card"><div class="value">{len(gaps)}</div><div class="label">Techniques left</div></div>
  </div>

  <section>
    <h2>Coverage by tactic</h2>
    <table><thead><tr><th>Tactic</th><th>Covered</th><th></th></tr></thead>
    <tbody>{tactic_rows}</tbody></table>
  </section>

  <section>
    <h2>Time to detect</h2>
    {ttd_section}
  </section>

  <section>
    <h2>Gaps — next up</h2>
    <ul>{gaps_rows if gaps else '<li class="muted">Everything cataloged is covered.</li>'}</ul>
  </section>
</div>
</body>
</html>
"""


def write_coverage(repo_root: Path, out_dir: Path | None = None) -> tuple[Path, Path]:
    out_dir = out_dir or (repo_root / "coverage")
    out_dir.mkdir(parents=True, exist_ok=True)

    layer_path = out_dir / LAYER_FILENAME
    layer_path.write_text(json.dumps(build_navigator_layer(repo_root), indent=2))

    report_path = out_dir / REPORT_FILENAME
    report_path.write_text(build_html_report(repo_root))

    return layer_path, report_path
